#' @title make.traits
#'
#' @description Making traits objects for dads
#'
#' @param n            The number of traits (default is 1)
#' @param start        The starting values for each traits (default is 0)
#' @param process      The trait process(es) (default is process.BM)
#' @param process.args An optional named list of optional arguments for the trait process
#' @param names        The optional names of the traits (generated by default from the process)
#' @param test         Logical whether to test if the traits object will work (default is TRUE)
#' 
#' @examples
#'
#' @seealso
#' 
#' @author Thomas Guillerme
#' @export

make.traits <- function() {

    output <- 42
    class(output) <- c("dads", "traits")
    return(output)
}