#' @title make.modifiers
#'
#' @description Making modifiers objects for dads
#'
#' @param when         When to apply the modifier
#' @param what         What value to modify
#' @param how          To which value
#' @param from         Optional, from which value to modify it (if left missing the current value is used)
#' @param modifier.args An optional named list of optional arguments for the trait process
#' @param names        The optional names of the modifiers (generated by default from the process)
#' @param test         Logical whether to test if the modifiers object will work (default is TRUE)
#' 
#' @examples
#'
#' @seealso
#' 
#' @author Thomas Guillerme
#' @export

make.modifiers <- function(when, from, to) {

    output <- 42
    class(output) <- c("dads", "modifiers")
    return(output)
}

# # ## The model for a modifier
# # modifier = list(
# #             # What to apply the modifier on (extinction, speciation or waiting time)
# #             what = "speciation",
# #             # What is the condition (<, <=, >=, ==, >)
# #             condition = `<`, # Distance from other traits or something like that
# #             # What is the value for the condition (a numeric)
# #             value = 0,
# #             # The modifier to multiply the probability with
# #             multiplier = 2 # Make this into a function (potentially)
# #     )

# ## Simple modifier
# change.from <- "extinction"
# change.to   <- "extinction" = 1
# change.when <- "traits.A" > 1


