---
title: "treats paper plots"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
bibliography: references.bib
output:
  html_document:
    fig_width: 8
    fig_height: 8
---

This script reproduces the plots and analyses used in the `treats` paper.

## Beck Lee data (figure 1)

```{r}
## Loading the data and packages
library(treats)
library(dispRity)
data(BeckLee_tree)
data(BeckLee_mat99)

## Creating the time slices
time_slices <- chrono.subsets(BeckLee_mat99, BeckLee_tree,
                              method = "continuous",
                              model  = "acctran",
                              time   = seq(from = 96, to = 36, by = -10))

## Calculating disparity on the two first dimensions only
observed_disparity <- dispRity(boot.matrix(time_slices), metric = c(sum, variances), dimensions = c(1,2))

## Plotting the tree and the disparity through time
pdf(file = "treats_example_figure1.pdf", width = 14, height = 7)
par(mfrow = c(1,2))
plot(BeckLee_tree, show.tip.label = FALSE)
axisPhylo()
abline(v = BeckLee_tree$root.time - 66, col = "red")
legend("topleft", pch = NULL, legend = "A", bty = "n", cex = 2)
par(bty = "n")
plot(observed_disparity, ylab = "Sum of variances")
abline(v = 4, col = "red")
legend("topleft", pch = NULL, legend = "B", bty = "n", cex = 2)
dev.off()
```

## Simulated tree

```{r}
## Using the birth-death parameters from the observed tree
my_bd_params <- crude.bd.est(BeckLee_tree)
## Setting the stopping rule (stop after 30 time units)
stop_rule <- list(max.time = 30)

## Generate the tree
set.seed(1)
sim_tree <- treats(bd.params  = my_bd_params,
                   stop.rule  = stop_rule,
                   null.error = 100)
pdf(file = "treats_example_figure2.pdf", width = 7, height = 7)
plot(sim_tree, show.tip.label = FALSE)
axisPhylo()
dev.off()
```

## Simulate tree and traits

```{r}
## Creating a trait in 97 dimensions.
my_traits <- make.traits(process = BM.process, n = 2)

## Simulate the tree and traits
set.seed(1)
sim_data <- treats(traits     = my_traits,
                   bd.params  = my_bd_params,
                   stop.rule  = stop_rule,
                   null.error = 100)
pdf(file = "treats_example_figure3.pdf", width = 14, height = 7)
par(mfrow = c(1,2))
plot(sim_data, ylab = "Trait 1", las = 1, main = "Trait 1 through time")
plot(sim_data, trait = c(2,1), ylab = "Trait 1", xlab = "Trait 2", las = 1, main = "Traits 1 and 2")
dev.off()
```

## Simulating a tree and traits with an extinction event


```{r}
## Creating a random mass extinction
random_extinction <- make.events(
    target       = "taxa",
    condition    = time.condition(15),
    modification = random.extinction(0.75))
## Creating an extinction that removes species with positive trait values
negative_extinction <- make.events(
    target = "taxa",
    condition = time.condition(15),
    modification = trait.extinction(x = 0, condition = `>=`))

set.seed(2)
sim_rand_extinction <- treats(
                   traits     = my_traits,
                   bd.params  = my_bd_params,
                   stop.rule  = stop_rule,
                   events     = random_extinction,
                   null.error = 100,
                   replicates = 50)

## Simulate the tree and traits with a random extinction event
sim_trait_extinction <- treats(
                   traits     = my_traits,
                   bd.params  = my_bd_params,
                   stop.rule  = stop_rule,
                   events     = negative_extinction,
                   null.error = 100,
                   replicates = 50)

pdf(file = "treats_example_figure4.pdf", width = 14, height = 7)
par(mfrow = c(1,2))
## Visualising the difference between both scenarios
plot(sim_rand_extinction[[11]], main = "Random extinction")
abline(v = 15, col = "red")
legend("topleft", pch = NULL, legend = "A", bty = "n", cex = 2)
plot(sim_trait_extinction[[10]], main = "Negative extinction")
legend("topleft", pch = NULL, legend = "B", bty = "n", cex = 2)
abline(v = 15, col = "red")
dev.off()
```

## Comparing disparities

```{r}
## Wrapper function for measuring disparity across the datasets
measure.disparity <- function(one_simulation) {
    ## transform the data
    sim <- dispRitreats(one_simulation, scale.tree = FALSE)
    ## Calculate disparity
    disparity <- dispRity(
             chrono.subsets(data = sim$data, tree = sim$tree,
                            method = "continuous", model = "acctran",
                            time = seq(from = 30, to = 0, by = -5)),
                            metric = c(sum, variances))
    ## Scale the disparity
    disparity <- unlist(get.disparity(disparity))
    return(disparity/max(disparity))
}

## Measuring disparities
random_extinction_disparity <- do.call(rbind, lapply(sim_rand_extinction, measure.disparity))
selective_extinction_disparity <- do.call(rbind, lapply(sim_trait_extinction, measure.disparity))

## Get the observed disparity
observed_disparity <- unlist(get.disparity(observed_disparity))
observed_disparity/max(observed_disparity)

## Plotting the results
polygon.plot <- function(disparity_results, main = "") {
    ## Get the quantiles
    quantiles <- apply(disparity_results, 2, quantile, probs = c(0.025, 0.25, 0.5, 0.75, 0.975), na.rm = TRUE)

    plot(NULL, xlim = c(1, ncol(quantiles)), ylim = range(quantiles), ylab = "scaled sum of ranges", xlab = "Relative time", main = main )
    polygon(x = c(1:ncol(quantiles), ncol(quantiles):1),
            y = c(quantiles[1, ], rev(quantiles[5, ])),
            col = "lightgrey", border = FALSE)
    polygon(x = c(1:ncol(quantiles), ncol(quantiles):1),
            y = c(quantiles[2, ], rev(quantiles[4, ])),
            col = "grey", border = FALSE)
    lines(x = c(1:ncol(quantiles)), y = quantiles[3, ])
}

pdf(file = "treats_example_figure5.pdf", width = 14, height = 7)
par(mfrow = c(1,2))
polygon.plot(random_extinction_disparity, main = "Random extinction")
abline(v = 4, col = "red")
lines(x = 1:7, y = observed_disparity, lty = 2, lwd = 2)
polygon.plot(selective_extinction_disparity, main = "Selective extinction")
abline(v = 4, col = "red")
lines(x = 1:7, y = observed_disparity, lty = 2, lwd = 2)
dev.off()
```